baseURL = "https://zzgcopilot.com"
languageCode = "zh-cn"
title = "ZZG Copilot Blog"
theme = "PaperMod"

[params]
  homeInfoParams = {Title = "欢迎来到 ZZG Copilot", Content = "分享技术教程与文章"}
    ShowReadingTime = true
      ShowShareButtons = true
        ShowPostNavLinks = true
          ShowBreadCrumbs = true
            ShowCodeCopyButtons = true

            [menu]
              [[menu.main]]
                  name = "文章"
                      url = "/posts/"
                          weight = 1
                            [[menu.main]]
                                name = "标签"
                                    url = "/tags/"
                                        weight = 2
                                          [[menu.main]]
                                              name = "关于"
                                                  url = "/about/"
                                                      weight = 3
